#!/usr/bin/env python3
"""Bundle assets/theme-demos/*.json into assets/theme-demos.js for file:// and Pages."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from theme_registry import EXPECTED_THEME_COUNT, load_theme_slugs

DEMOS_DIR = ROOT / "assets" / "theme-demos"
DEMOS_JS = ROOT / "assets" / "theme-demos.js"


def load_demo_files() -> dict[str, dict]:
    if not DEMOS_DIR.is_dir():
        raise FileNotFoundError(f"Missing demo directory: {DEMOS_DIR}")
    bundled: dict[str, dict] = {}
    for path in sorted(DEMOS_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError(f"{path.name} must be a JSON object")
        bundled[path.stem] = data
    return bundled


def render_js(bundled: dict[str, dict]) -> str:
    payload = json.dumps(bundled, ensure_ascii=False, indent=2)
    return f"// Generated by scripts/build_theme_demos.py — edit assets/theme-demos/<slug>.json\n(() => {{\nglobalThis.SLIDES_THEME_DEMOS = {payload};\n}})();\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Bundle per-theme demo JSON into theme-demos.js.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if theme-demos.js is out of date (for CI).",
    )
    args = parser.parse_args()

    expected_slugs = set(load_theme_slugs())
    bundled = load_demo_files()
    found_slugs = set(bundled)

    errors: list[str] = []
    missing = sorted(expected_slugs - found_slugs)
    extra = sorted(found_slugs - expected_slugs)
    if missing:
        errors.append(f"Missing demo JSON for: {', '.join(missing)}")
    if extra:
        errors.append(f"Unknown demo JSON files: {', '.join(extra)}")
    if len(expected_slugs) != EXPECTED_THEME_COUNT:
        errors.append(f"Expected {EXPECTED_THEME_COUNT} theme slugs, found {len(expected_slugs)}")

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    expected_js = render_js(bundled)

    if args.check:
        if not DEMOS_JS.exists():
            print(f"ERROR: {DEMOS_JS} missing — run python3 scripts/build_theme_demos.py")
            return 1
        current = DEMOS_JS.read_text(encoding="utf-8")
        if current != expected_js:
            print(f"ERROR: {DEMOS_JS} is out of sync with assets/theme-demos/")
            print("Run: python3 scripts/build_theme_demos.py")
            return 1
        print(f"OK: {DEMOS_JS.name} matches {len(bundled)} demo JSON files")
        return 0

    DEMOS_JS.write_text(expected_js, encoding="utf-8")
    print(f"Wrote {len(bundled)} demos to {DEMOS_JS}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
