#!/usr/bin/env python3
"""Validate self-contained HTML slide decks generated by the slides skill."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path
from typing import Any


ALLOWED_TYPES = {
    "cover",
    "section-intro",
    "statement",
    "two-column",
    "three-column",
    "big-number",
    "comparison",
    "quote",
    "flow",
    "code",
    "layer-stack",
    "diagram",
    "stats-row",
    "four-grid",
    "timeline",
    "end",
    "interactive-question",
    "breath",
    "hero-image",
}

ALLOWED_RHYTHMS = {"anchor", "dense", "breath"}
LABEL_FORBIDDEN_TYPES = {"statement", "quote", "big-number", "end", "breath"}


@dataclass
class Slide:
    attrs: dict[str, str]
    html: str = ""
    text: str = ""
    classes: set[str] = field(default_factory=set)

    @property
    def declared_type(self) -> str:
        return self.attrs.get("data-slide-type", "").strip()

    @property
    def rhythm(self) -> str:
        return self.attrs.get("data-rhythm", "").strip()

    @property
    def is_active(self) -> bool:
        return "active" in self.classes

    @property
    def has_label(self) -> bool:
        return re.search(r'class=["\'][^"\']*\blabel\b', self.html) is not None

    @property
    def has_callout(self) -> bool:
        return re.search(r'class=["\'][^"\']*\bcallout\b', self.html) is not None


class DeckParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.slides: list[Slide] = []
        self._current: Slide | None = None
        self._depth = 0

    def handle_starttag(self, tag: str, attrs_list: list[tuple[str, str | None]]) -> None:
        attrs = {key: value or "" for key, value in attrs_list}
        attr_text = "".join(
            f' {key}="{value}"' if value is not None else f" {key}"
            for key, value in attrs_list
        )
        raw = f"<{tag}{attr_text}>"
        classes = set(attrs.get("class", "").split())

        if tag == "div" and "slide" in classes and self._current is None:
            self._current = Slide(attrs=attrs, classes=classes, html=raw)
            self._depth = 1
            return

        if self._current is not None:
            self._current.html += raw
            if tag == "div":
                self._depth += 1

    def handle_endtag(self, tag: str) -> None:
        if self._current is None:
            return

        self._current.html += f"</{tag}>"
        if tag == "div":
            self._depth -= 1
            if self._depth == 0:
                self.slides.append(self._current)
                self._current = None

    def handle_data(self, data: str) -> None:
        if self._current is not None:
            self._current.html += data
            self._current.text += data + " "


def parse_notes(html: str) -> list[str]:
    match = re.search(r"\b(?:var|const|let)\s+NOTES\s*=\s*\[(.*?)\]\s*;", html, re.S)
    if not match:
        return []
    body = match.group(1)
    notes: list[str] = []
    i = 0
    while i < len(body):
        while i < len(body) and body[i] not in {"'", '"', "`"}:
            i += 1
        if i >= len(body):
            break
        quote = body[i]
        i += 1
        chars: list[str] = []
        while i < len(body):
            ch = body[i]
            if ch == "\\" and i + 1 < len(body):
                chars.append(body[i + 1])
                i += 2
                continue
            if ch == quote:
                i += 1
                break
            chars.append(ch)
            i += 1
        notes.append("".join(chars).strip())
    return notes


def parse_deck_lock(html: str) -> tuple[dict[str, Any] | None, str | None]:
    match = re.search(
        r'<script[^>]*id=["\']deck-lock["\'][^>]*>(.*?)</script>',
        html,
        re.S | re.I,
    )
    if not match:
        return None, None
    raw = match.group(1).strip()
    if not raw or "{{" in raw:
        return None, "deck-lock script is empty or still contains template placeholders"
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        return None, f"deck-lock JSON is invalid: {exc}"
    if not isinstance(parsed, dict):
        return None, "deck-lock JSON must be an object"
    return parsed, None


def infer_type(slide: Slide) -> str:
    if slide.declared_type:
        return slide.declared_type
    html = slide.html
    classes = slide.classes
    if "cover" in classes:
        return "cover"
    if "section-intro" in classes:
        return "section-intro"
    if "end-slide" in classes:
        return "end"
    checks = [
        ("big-number", "big-number"),
        ("quote-block", "quote"),
        ("compare", "comparison"),
        ("flow-visual", "flow"),
        ("layer-stack", "layer-stack"),
        ("stat-row", "stats-row"),
        ("four-grid", "four-grid"),
        ("three-col", "three-column"),
        ("two-col", "two-column"),
        ("mono", "code"),
    ]
    for token, slide_type in checks:
        if token in html:
            return slide_type
    if "<svg" in html:
        return "diagram"
    return "statement"


def word_count(text: str) -> int:
    latin = re.findall(r"[A-Za-z0-9]+(?:[-'][A-Za-z0-9]+)?", text)
    cjk = re.findall(r"[\u4e00-\u9fff]", text)
    return len(latin) + len(cjk)


def validate(path: Path) -> tuple[list[str], list[str], dict[str, Any]]:
    html = path.read_text(encoding="utf-8")
    parser = DeckParser()
    parser.feed(html)
    slides = parser.slides
    notes = parse_notes(html)
    deck_lock, deck_lock_error = parse_deck_lock(html)

    errors: list[str] = []
    warnings: list[str] = []

    if "{{" in html or "}}" in html:
        errors.append("Template placeholders remain in the HTML.")

    if not slides:
        errors.append("No .slide elements found.")
        return errors, warnings, {"slides": 0, "notes": len(notes)}

    active_count = sum(1 for slide in slides if slide.is_active)
    if active_count != 1:
        errors.append(f"Expected exactly one active slide, found {active_count}.")
    elif not slides[0].is_active:
        errors.append("The first slide must be the active slide.")

    if not notes:
        errors.append("NOTES array was not found or is empty.")
    elif len(notes) != len(slides):
        errors.append(f"Slide count ({len(slides)}) does not match NOTES count ({len(notes)}).")
    else:
        for index, note in enumerate(notes, start=1):
            if not note:
                errors.append(f"Slide {index:02d} has an empty speaker note.")

    if deck_lock_error:
        errors.append(deck_lock_error)
    if deck_lock:
        locked_slides = deck_lock.get("slides", [])
        if not isinstance(locked_slides, list):
            errors.append("deck-lock slides must be an array.")
        elif locked_slides and len(locked_slides) != len(slides):
            errors.append(
                f"deck-lock slide count ({len(locked_slides)}) does not match HTML slides ({len(slides)})."
            )
    else:
        warnings.append("deck-lock JSON not found; new decks should embed the contract for validation.")

    if "fonts.googleapis.com" not in html:
        warnings.append("Google Fonts URL not found; confirm the selected font is available.")

    required_js = ["function updateNotes", "function go", "hashchange", "keydown", "scaleDeck"]
    for token in required_js:
        if token not in html:
            errors.append(f"Required slide engine token missing: {token}")

    inferred_types = [infer_type(slide) for slide in slides]
    label_slides = 0
    callout_count = 0
    breath_or_hero = False

    for index, (slide, slide_type) in enumerate(zip(slides, inferred_types), start=1):
        if slide.declared_type:
            if slide.declared_type not in ALLOWED_TYPES:
                errors.append(f"Slide {index:02d} has unknown data-slide-type: {slide.declared_type}")
        else:
            warnings.append(f"Slide {index:02d} has no data-slide-type; inferred {slide_type}.")

        if slide.rhythm:
            if slide.rhythm not in ALLOWED_RHYTHMS:
                errors.append(f"Slide {index:02d} has unknown data-rhythm: {slide.rhythm}")
        else:
            warnings.append(f"Slide {index:02d} has no data-rhythm.")

        if slide.has_label:
            label_slides += 1
            if slide_type in LABEL_FORBIDDEN_TYPES:
                warnings.append(f"Slide {index:02d} ({slide_type}) uses .label, which weakens this slide type.")

        if slide.has_callout:
            callout_count += len(re.findall(r'class=["\'][^"\']*\bcallout\b', slide.html))

        if slide_type in {"breath", "hero-image"} or slide.rhythm == "breath":
            breath_or_hero = True

        count = word_count(slide.text)
        if count > 90:
            warnings.append(f"Slide {index:02d} has about {count} words/chars; consider splitting it.")

    for index in range(1, len(inferred_types)):
        if inferred_types[index] == inferred_types[index - 1]:
            warnings.append(
                f"Slides {index:02d} and {index + 1:02d} repeat type {inferred_types[index]}."
            )

    label_ratio = label_slides / len(slides)
    if label_ratio > 0.4:
        warnings.append(f"Labels appear on {label_ratio:.0%} of slides; target is under 40%.")

    if callout_count > 2:
        warnings.append(f"Found {callout_count} callout boxes; target maximum is 2.")

    if len(slides) >= 8 and not breath_or_hero:
        warnings.append("Deck has 8+ slides but no breath or hero-image pacing slide.")

    summary = {
        "slides": len(slides),
        "notes": len(notes),
        "labels": label_slides,
        "callouts": callout_count,
        "types": inferred_types,
        "has_deck_lock": deck_lock is not None,
    }
    return errors, warnings, summary


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate a slides-skill HTML deck.")
    parser.add_argument("html", type=Path, help="Path to the generated HTML deck")
    parser.add_argument("--strict", action="store_true", help="Treat warnings as failures")
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON")
    args = parser.parse_args()

    errors, warnings, summary = validate(args.html)
    failed = bool(errors) or (args.strict and bool(warnings))

    if args.json:
        print(json.dumps({"ok": not failed, "errors": errors, "warnings": warnings, "summary": summary}, indent=2))
    else:
        status = "PASS" if not failed else "FAIL"
        print(f"{status}: {args.html}")
        print(f"Slides: {summary.get('slides', 0)} | Notes: {summary.get('notes', 0)}")
        for error in errors:
            print(f"ERROR: {error}")
        for warning in warnings:
            print(f"WARNING: {warning}")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
